import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, registerMainMenuItem, urlButton } from "../toolkit/index.js";
import { getPaid } from "../registrar-data.js";
import { askTeam } from "./register-start.js";
registerMainMenuItem({ label: "Open paid registration", data: "paid:register", order: 30 });
const composer = new Composer<Ctx>();
composer.callbackQuery("paid:register", async (ctx) => { await ctx.answerCallbackQuery(); const settings = await getPaid(ctx); if (!settings.enabled) { await ctx.reply("Paid registration isn't enabled yet.", { reply_markup: inlineKeyboard([[inlineButton("Back to menu", "menu:main")]]) }); return; } if (!settings.price || !settings.paymentLink) { await ctx.reply("Paid registration isn't configured yet. Contact the organizer."); return; } ctx.session.registrar = { step: "paid-confirm" }; await ctx.reply(`Registration costs ${settings.price}. Complete payment, then confirm here.`, { reply_markup: inlineKeyboard([[urlButton("Open payment link", settings.paymentLink)], [inlineButton("I've paid", "paid:confirm")], [inlineButton("Back to menu", "menu:main")]]) }); });
composer.callbackQuery("paid:confirm", async (ctx) => { await ctx.answerCallbackQuery(); if (ctx.session.registrar?.step !== "paid-confirm") { await ctx.reply("Open paid registration first, then confirm payment."); return; } await askTeam(ctx, true); });
export default composer;
