import type { Ctx } from "./bot.js";

export type Locale = "en" | "ru";
type Values = Record<string, string | number>;

const ru: Record<string, string | ((v: Values) => string)> = {
  "welcome": "Добро пожаловать в реестр команд. Выберите действие.",
  "help": "Используйте меню, чтобы зарегистрировать команду, посмотреть турнирную таблицу или открыть платную регистрацию.\n\nОрганизаторы управляют конфликтами и результатами в панели администратора.",
  "menu.register:start": "Регистрация команды", "menu.view:teams": "Команды и таблица", "menu.paid:register": "Платная регистрация", "menu.admin:desk": "Панель администратора", "menu.help": "Помощь", "menu.language": "Язык",
  "back": "В меню", "cancel": "Отмена", "confirm": "Подтвердить регистрацию", "type": "Введите ответ",
  "lang.choose": "Выберите язык.", "lang.saved.ru": "Выбран русский язык.", "lang.saved.en": "English selected.", "lang.ru": "Русский", "lang.en": "English",
  "unavailable.records": "Данные турнира пока недоступны. Попробуйте позже.", "register.unavailable": "Данные регистрации пока недоступны. Попробуйте позже.",
  "register.team": "Введите название команды.", "register.name.invalid": "Название команды должно быть от 2 до 40 символов.", "register.phone": "Введите контактный номер капитана.", "register.phone.invalid": "Введите корректный контактный номер.", "register.count": "Сколько основных игроков регистрируется?", "register.player": v => `Введите игрока ${v.n} из ${v.total}: игровой ID | никнейм | роль.`, "register.player.format": "Используйте формат: игровой ID | никнейм | роль.", "register.player.duplicate": "Этот игровой ID уже есть в команде. Используйте другой.", "register.subs.ask": "Добавить запасных игроков?", "register.subs.yes": "Добавить запасного", "register.subs.no": "Без запасных", "register.sub": "Введите запасного: игровой ID | никнейм | роль. Когда закончите, отправьте «Готово».", "register.sub.format": "Используйте формат: игровой ID | никнейм | роль, или отправьте «Готово».", "register.sub.added": "Запасной добавлен. Добавьте следующего или отправьте «Готово».", "register.sub.required": "Добавьте хотя бы одного запасного или выберите «Без запасных».", "register.review": "Проверьте регистрацию и подтвердите её.", "register.cancelled": "Регистрация отменена.", "register.existing": "У вас уже есть регистрация команды. Если нужны изменения, обратитесь к организатору.", "register.saved": "Ваша команда зарегистрирована и активна.", "register.pending": "Ваша регистрация ожидает проверки конфликта ID.", "register.owner.unset": "Уведомления организатора ещё не настроены.", "register.save.error": "Не удалось сохранить регистрацию. Попробуйте позже.",
  "paid.unavailable": "Платная регистрация пока недоступна. Попробуйте позже.", "paid.closed": "Платная регистрация сейчас закрыта.", "paid.instructions": v => `Взнос: ${v.price}. Оплатите регистрацию, затем подтвердите её здесь.`, "paid.open": "Открыть оплату", "paid.confirm": "Подтвердить оплату",
  "teams.empty": "Команд пока нет — выберите «Регистрация команды», чтобы добавить команду.", "teams.title": "Команды и таблица", "teams.match": "Матч", "teams.line": v => `${v.wins} ${pluralRu(Number(v.wins), "победа", "победы", "побед")} / ${v.losses} ${pluralRu(Number(v.losses), "поражение", "поражения", "поражений")}`,
  "admin.desk": "Управляйте регистрациями, результатами и платным доступом.", "admin.conflicts": "Разрешить конфликты", "admin.match": "Добавить результат", "admin.paid": "Платная регистрация", "admin.no.conflicts": "Конфликтов игровых ID для проверки нет.", "admin.conflict.choose": v => `Выберите активную команду для общего игрового ID «${v.ids}».\n1. ${v.one}\n2. ${v.two}\n\nОтветьте 1 или 2.`, "admin.reply.choice": "Ответьте 1 или 2.", "admin.conflict.incomplete": "Данные этого конфликта неполные. Попробуйте позже.", "admin.conflict.gone": "Этот конфликт больше недоступен.", "admin.conflict.resolved": v => `${v.winner} активна. ${v.loser} не одобрена.`, "admin.need.teams": "Добавьте хотя бы две активные команды перед записью матча.", "admin.winner": "Выберите победившую команду.", "admin.loser": "Выберите проигравшую команду.", "admin.link": "Введите ссылку на матч.", "admin.link.invalid": "Введите полную ссылку на матч, начинающуюся с https://.", "admin.teams.gone": "Эти команды больше недоступны.", "admin.match.live": "Результат матча опубликован в таблице.", "admin.paid.on": v => `Платная регистрация включена: ${v.price}.`, "admin.paid.off": "Платная регистрация выключена.", "admin.paid.enable": "Включить платную регистрацию", "admin.paid.disable": "Выключить платную регистрацию", "admin.paid.set": "Установить цену и ссылку", "admin.paid.need.details": "Укажите цену и ссылку на оплату до включения платной регистрации.", "admin.paid.opened": "Платная регистрация открыта.", "admin.paid.closed": "Платная регистрация закрыта.", "admin.price": "Введите стоимость регистрации с валютой.", "admin.price.invalid": "Введите короткую стоимость с валютой.", "admin.payment.link": "Введите защищённую ссылку для подтверждения оплаты.", "admin.link.invalid.generic": "Введите полную ссылку, начинающуюся с https://.", "admin.payment.saved": "Данные оплаты сохранены. Включите платную регистрацию, когда будете готовы.",
  "notify.conflict": v => `Конфликт игрового ID: ${v.team} конфликтует с ${v.other}. Откройте панель администратора для решения.`, "notify.team": v => `Новая регистрация команды: ${v.team}. Откройте панель администратора для управления турниром.`,
};

const en: Record<string, string | ((v: Values) => string)> = {
  "welcome": "Welcome to the team registrar. Choose an option below.", "help": "Use the menu to register a team, view standings, or open paid registration.\n\nOrganizers can manage conflicts and match results from Admin desk.",
  "menu.register:start": "Register team", "menu.view:teams": "Teams and table", "menu.paid:register": "Paid registration", "menu.admin:desk": "Admin desk", "menu.help": "❓ Help", "menu.language": "Language", "back": "Back to menu", "cancel": "Cancel", "confirm": "Confirm registration", "type": "Type your answer",
  "lang.choose": "Choose your language.", "lang.saved.ru": "Russian selected.", "lang.saved.en": "English selected.", "lang.ru": "Русский", "lang.en": "English",
  "unavailable.records": "Tournament records aren't available yet. Try again shortly.", "register.unavailable": "Registration records aren't available yet. Try again shortly.", "register.team": "Enter your team name.", "register.name.invalid": "Use a team name between 2 and 40 characters.", "register.phone": "Enter a captain contact number.", "register.phone.invalid": "Enter a valid contact number.", "register.count": "How many starting players are registering?", "register.player": v => `Enter player ${v.n} of ${v.total} as: game ID | nickname | role.`, "register.player.format": "Use: game ID | nickname | role.", "register.player.duplicate": "That game ID is already on this team. Use a different one.", "register.subs.ask": "Do you want to add substitutes?", "register.subs.yes": "Add substitute", "register.subs.no": "No substitutes", "register.sub": "Enter a substitute as: game ID | nickname | role. Send Done when finished.", "register.sub.format": "Use: game ID | nickname | role, or send Done.", "register.sub.added": "Substitute added. Add another or send Done.", "register.sub.required": "Add at least one substitute or tap No substitutes.", "register.review": "Review your registration, then confirm it.", "register.cancelled": "Registration cancelled.", "register.existing": "You already have a team registration. Ask the organizer to update it if needed.", "register.saved": "Your team is registered and active.", "register.pending": "Your registration is pending an ID conflict review.", "register.owner.unset": "Owner notifications aren't set up yet.", "register.save.error": "Couldn't save this registration. Try again shortly.",
  "paid.unavailable": "Paid registration isn't available yet. Try again shortly.", "paid.closed": "Paid registration isn't open right now.", "paid.instructions": v => `Registration fee: ${v.price}. Complete payment, then confirm here.`, "paid.open": "Open payment", "paid.confirm": "Confirm payment", "teams.empty": "No registered teams yet — tap Register team to add one.", "teams.title": "Teams and standings", "teams.match": "Match", "teams.line": v => `${v.wins}W / ${v.losses}L`,
  "admin.desk": "Manage registrations, results, and paid access.", "admin.conflicts": "Resolve conflicts", "admin.match": "Add match result", "admin.paid": "Paid registration", "admin.no.conflicts": "No game ID conflicts need review.", "admin.conflict.choose": v => `Choose the active team for the shared game ID.\n1. ${v.one}\n2. ${v.two}\n\nReply with 1 or 2.`, "admin.reply.choice": "Reply with 1 or 2.", "admin.conflict.incomplete": "That conflict record is incomplete. Try again shortly.", "admin.conflict.gone": "That conflict is no longer available.", "admin.conflict.resolved": v => `${v.winner} is active. ${v.loser} was not approved.`, "admin.need.teams": "Add at least two active teams before recording a match.", "admin.winner": "Choose the winning team.", "admin.loser": "Choose the losing team.", "admin.link": "Enter the match link.", "admin.link.invalid": "Enter a full match link starting with https://.", "admin.teams.gone": "Those teams are no longer available.", "admin.match.live": "Match result is live in the table.", "admin.paid.on": v => `Paid registration is on at ${v.price}.`, "admin.paid.off": "Paid registration is off.", "admin.paid.enable": "Enable paid registration", "admin.paid.disable": "Disable paid registration", "admin.paid.set": "Set price and link", "admin.paid.need.details": "Set a price and payment link before enabling paid registration.", "admin.paid.opened": "Paid registration is now open.", "admin.paid.closed": "Paid registration is now closed.", "admin.price": "Enter the registration price, including currency.", "admin.price.invalid": "Enter a short price, including currency.", "admin.payment.link": "Enter the secure payment confirmation link.", "admin.link.invalid.generic": "Enter a full link starting with https://.", "admin.payment.saved": "Payment details saved. Enable paid registration when you're ready.", "notify.conflict": v => `Game ID conflict: ${v.team} conflicts with ${v.other}. Open Admin desk to resolve it.`, "notify.team": v => `New team registration: ${v.team}. Open Admin desk to manage the tournament.`,
};

function pluralRu(value: number, one: string, few: string, many: string): string {
  const mod100 = Math.abs(value) % 100, mod10 = Math.abs(value) % 10;
  return mod100 > 10 && mod100 < 20 ? many : mod10 === 1 ? one : mod10 > 1 && mod10 < 5 ? few : many;
}

export function locale(ctx: Ctx): Locale { return ctx.session.locale ?? (ctx.from?.language_code?.toLowerCase().startsWith("ru") ? "ru" : "en"); }
export function t(ctx: Ctx, key: string, values: Values = {}): string {
  const value = (locale(ctx) === "ru" ? ru[key] : undefined) ?? en[key] ?? key;
  return typeof value === "function" ? value(values) : value;
}
export function typed(ctx: Ctx) { return { force_reply: true, input_field_placeholder: t(ctx, "type") } as const; }
